Improve CI results against rails edge (#1297)
* Exclude rails edge + ruby 2.4 combination from CI

Because Rails master no longer supports ruby 2.4.

* Bump sqlite3 dev dependency

Rails master has an implicit requirement on sqlite 1.4 or higher.
Bumping the development dependency should fix that issue on our
rails edge CI entries.

* Fix rails edge error when generating test application

In particular,

```
LoadError: cannot load such file -- bootsnap/setup
```

produced while booting the generated application, because rails
`config/boot.rb` uses bootsnap by default, but our Gemfile does not
include it.

We don't really need bootsnap, so skip it.

* Fix rails version in generated Rails application

Previously in the case of Rails >= 6, both replacements were being
applied, resulting in Rails 5.2 being used instead of Rails 6 or higher,
causing the following error:

```
(...)
Fetching https://github.com/rails/rails.git
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'rails (~> 6.1.0.alpha)' in
https://github.com/rails/rails.git (at 5-2-stable@32cfb82).
The source contains 'rails' at: 5.2.4.1
```

* Fix another generated application error

During test application generation under Rails 6 or higher,
`webpacker:install` fails to run with the following error:

```
       rails  webpacker:install
rails aborted!
Don't know how to build task 'webpacker:install' (See the list of available tasks with `rails --tasks`)
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/command.rb:47:in `invoke'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/generators/actions.rb:257:in `block (2 levels) in rails_command'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activesupport/lib/active_support/core_ext/kernel/reporting.rb:15:in `block in silence_warnings'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activesupport/lib/active_support/core_ext/kernel/reporting.rb:28:in `with_warnings'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activesupport/lib/active_support/core_ext/kernel/reporting.rb:15:in `silence_warnings'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/generators/actions.rb:256:in `block in rails_command'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/actions.rb:197:in `block in in_root'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/actions.rb:187:in `block in inside'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/actions.rb:187:in `inside'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/actions.rb:197:in `in_root'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/generators/actions.rb:255:in `rails_command'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/generators/app_base.rb:419:in `run_webpack'
(eval):1:in `run_webpack'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/commands/application/application_command.rb:26:in `perform'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/command/base.rb:69:in `perform'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/command.rb:45:in `invoke'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/cli.rb:18:in `<top (required)>'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/exe/rails:10:in `require'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/exe/rails:10:in `<top (required)>'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bin/rails:23:in `load'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bin/rails:23:in `<main>'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bin/ruby_executable_hooks:24:in `eval'
/path/to/formtastic/vendor/bundle/ruby/2.5.0/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
The command "script/integration.sh" exited with 1.
```

We fix it by generating the dummy application without javascript, since
it's not really needed.

* Leave sqlite3 alone in generated application

Unconditionally replacing this leads to errors like:

```
       rails  generate scaffold user name:string password:digest
      invoke  active_record
Traceback (most recent call last):
  51: from bin/rails:4:in `<main>'
  50: from bin/rails:4:in `require'
  48: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/command.rb:45:in `invoke'
  47: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/command/base.rb:69:in `perform'
  46: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  45: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  44: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  43: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/commands/generate/generate_command.rb:26:in `perform'
  42: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/generators.rb:272:in `invoke'
  41: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  40: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
  39: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
  38: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
  37: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
  36: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
  35: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  34: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  33: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/group.rb:134:in `_invoke_from_option_orm'
  32: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/group.rb:266:in `_invoke_for_class_method'
  31: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/shell.rb:68:in `with_padding'
  30: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/group.rb:277:in `block in _invoke_for_class_method'
  29: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
  28: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
  27: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
  26: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
  25: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
  24: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
  23: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  22: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  21: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activerecord/lib/rails/generators/active_record/model/model_generator.rb:23:in `create_migration_file'
  20: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/generators/named_base.rb:88:in `table_name'
  19: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/railties/lib/rails/generators/named_base.rb:197:in `pluralize_table_names?'
  18: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
  17: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
  16: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activerecord/lib/active_record/base.rb:17:in `<top (required)>'
  15: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activerecord/lib/active_record/base.rb:317:in `<module:ActiveRecord>'
  14: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activesupport/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
  13: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activesupport/lib/active_support/lazy_load_hooks.rb:51:in `each'
  12: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activesupport/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
  11: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activesupport/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
  10: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activesupport/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
   9: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activesupport/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
   8: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activesupport/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
   7: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activerecord/lib/active_record/railtie.rb:212:in `block (2 levels) in <class:Railtie>'
   6: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activerecord/lib/active_record/connection_handling.rb:52:in `establish_connection'
   5: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:1045:in `establish_connection'
   4: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:1197:in `resolve_pool_config'
   3: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
   2: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
   1: from /path/to/formtastic/vendor/bundle/ruby/2.5.0/bundler/gems/rails-1ef8c60dfcab/activerecord/lib/active_record/connection_adapters/sqlite3_adapter.rb:13:in `<top (required)>'

/home/travis/.rvm/gems/ruby-2.5.7/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:346:in `block (2 levels) in replace_gem': Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-1.3.13. Make sure all dependencies are added to Gemfile. (LoadError)
```